const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

const option = {
    swaggerDefinition: {
        info: {
            title: 'REST API',
            version: '1.0.0',
            description: 'Test Express API with autogenerated swagger doc'
        },
        // securityDefinitions: {
        //     JWT: {
        //         type: 'apiKey',
        //         description: 'Ex: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9....',
        //         name: 'Authorization',
        //         in: 'header'
        //     }
        // },
        // security: [{
        //     'JWT': []
        // }],
        host: 'localhost:3000',
        basePath: '/'
    },
    apis: ["./src/routes/*.js"]
};

const swaggerSpec = swaggerJsdoc(option);

module.exports = (app) => {
    app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
}
